name: Create Artifacts

on: [workflow_dispatch]
jobs:
  build:
    name: Create a Dummy Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  Create Artifact
        run: |
          echo "Creating file...."
          echo "This is an artifact created with echo." > output.txt
          echo ""

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dummy-artifact.txt
          path: output.txt

  test:
    name: Download Dummy Artifact
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: dummy-artifact.txt
      - name: Make readable
        run: chmod +x dummy_artifact.txt
      - name: Test Artifact
        run: |
          echo "Testing download artifact..."
          cat dummy-artifact.txt
      
