name: Multi-Job Workflow
on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    - name: checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5
      with:
        go-version: "1.20"

    - name: Build Go Binary
      run: go build -o main main.go

    - name: Run binary
      run ./main
  windows:
    runs-on: windows-latest
  macos:
    runs-on: ubuntu-latest
  cross-compile:
    runs-on: ubuntu-latest
